---
stages:
  - test
  - build

.create_multi_arch_image:
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  before_script:
    - docker version
    - docker info | grep Registry
    - echo -n $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin
    - docker info | grep Registry
    - echo $CI_REGISTRY_IMAGE
    - apk add curl
    - mkdir -vp ~/.docker/cli-plugins/
    - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --name job-$CI_JOB_ID
    - docker buildx inspect --bootstrap
  after_script:
    - docker logout
    - docker rm buildx_buildkit_job-${CI_JOB_ID}0 --force || true
  tags:
    - dind

docker_build:
  extends: .create_multi_arch_image
  stage: build
  script:
    - build_tags=""
    - |
      if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]
      then
        build_tags = "--tag ${DOCKERHUB_IMAGE}:latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': ${build_tags}"
      elif [ -n "$CI_COMMIT_TAG" ]
      then
        MAJOR_VERSION=$(echo "$CI_COMMIT_TAG" | awk -F'.' '{print $1}')
        MAJOR_MINOR_VERSION=$(echo "$CI_COMMIT_TAG" | awk -F'.' '{print $1"."$2}')
        VERSION=$([[ $(echo $CI_COMMIT_REF_NAME | cut -d'-' -f1) == release ]] && echo $CI_COMMIT_REF_NAME | cut -d'-' -f2 || echo $CI_COMMIT_REF_NAME)
        tag=":$VERSION"
        echo "Version: ${VERSION}, Major Version: ${MAJOR_VERSION}, Major Minor Version: ${MAJOR_MINOR_VERSION}"
        #echo "Running on tag release '$VERSION': tag = $tag"
        build_tags="--tag ${DOCKERHUB_IMAGE}:${VERSION} --tag ${DOCKERHUB_IMAGE}:${MAJOR_VERSION} --tag ${DOCKERHUB_IMAGE}:${MAJOR_MINOR_VERSION}"
        echo "New Build Tag is ${build_tags}"
      else
        echo "Running on branch '$CI_COMMIT_BRANCH': build_tags = ${DOCKERHUB_IMAGE}:${CI_COMMIT_REF_SLUG}"
      fi
    - docker buildx build --build-arg BUILD_VERSION=$CI_COMMIT_REF_NAME --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --platform linux/amd64,linux/arm64 $build_tags --push image
    - docker manifest inspect $DOCKERHUB_IMAGE${tag}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: ('$CI_PIPELINE_SOURCE == "merge_request_event"' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH)
      changes:
        - image/Dockerfile
        - .gitlab-ci.yml
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - image/**/*
    - if: $CI_COMMIT_TAG
      changes:
        - image/**/*
